import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import "./globals.css";

import classNames from "classnames/bind";
import styles from "../css/defaultLayout.module.scss";

const cx = classNames.bind(styles);

export const metadata = {
  title: "Tik tok",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={cx("wrapper")}>
          <Header />
          {/* <div className={cx("container")}>
            <Sidebar />
            <div className={cx("content")}>{children}</div>
          </div> */}
        </div>
      </body>
    </html>
  );
}
