import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import "./globals.scss";

export const metadata = {
  title: "Tik tok",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          <div className="container">
            <Sidebar />
            <div className="content">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
